### ISSUE TITLE
The use of get_graph_feature_cross in vn_pointnet.py

### ISSUE THREAD

**Issue by lapatric** [FlyingGiraffe/vnn#1]
Hi 

Could you please explain the purpose of ```get_graph_feature_cross``` in l.76 of ```vn_pointnet.py```?
It doesn't seem that this function has any equivalent in the original implementation of pointnet.

Thanks!

**Comment by FlyingGiraffe** [comment]
Hi,

Thanks for the question. This is discussed at the end of Section 4 in the paper. If you apply per-point transformations to the 1*3 coordinates directly, the resulting per-point C*3 feature will have all its vector channels linearly dependent (analogous to applying a per-pixel 1x1 convolution to a gray-scale image). Thus we add an edge convolution at the input layer to tackle this issue. The additional "cross product" to the original `get_graph_feature` in DGCNN is to make the input 3*3 instead of 2*3, so that vectors in the output C*3 feature won't be restricted to a 2D plane.

Congyue
