### ISSUE TITLE
Is equation 15 (in chapter 3.5 Invariant Layers of your paper) correctly implemented?

### ISSUE THREAD

**Issue by lapatric** [FlyingGiraffe/vnn#2]
Hi

The invariant layer defined in chapter 3.5 of your paper (specifically equations 14 and 15) appears to be implemented in the ```VNStdFeature``` module defined in ```vn_layers.py``` and it is used by the VN-PointNetEncoder in l.92 of ```vn_pointnet.py```. What I do not understand, is that in equation 15 of the paper you write ```V_n*T_n.transpose()```, however, in the code it appears to me that you instead compute ```[V_n, V_n.mean()]*T_n.transpose()``` (l.191 of ```vn_pointnet.py```). This is because in the code, x (which is the input to the module ```VNStdFeature``` formed in l.91 of ```vn_pointnet.py```) is the concatenated tensor [V_n, V_n.mean()] . Also, for clarification, I understand ```T_n``` (defined in equation 14 of the paper) to be the output ```z0``` in l.170 of ```vn_layers.py```.

An answer as to why equation 15 doesn't appear to be aligned with the code would be be greatly appreciated. Thanks

**Comment by FlyingGiraffe** [comment]
Hi,

Thanks for the question, this is a very nice point. You're right, what is computed in the code is indeed `[V_n, V_n.mean()]*T_n.transpose()`. Equation 15 in the paper is just a general formulation for attaining invariance, while in practice `T_n` can be multiplied to any Cx3 feature and this does not break equivariance/invariance. (Maybe also note that at line 81 in `vn_dgcnn_partseg.py`, we apply `T_n` computed from `x` to `x123` directly instead of computing a separate `T_n` for `x123`.)

BTW, if you're interested in the effect of this concatenation with `V_n.mean()`, you may refer to the ablation study (Table 8) in the supplementary material.

Congyue

**Comment by lapatric** [comment]
Thanks for the clarification :)
